[default.general]
chip = "RP2040"
log_level = "WARN"
connect_under_reset = false # RP2040 does not support connect_under_reset

[default.flashing]
enabled = true

[default.reset]
enabled = true
halt_afterwards = false

[default.probe]
protocol = "Swd"
speed = 1000

[default.rtt]
enabled = true
up_mode = "NoBlockSkip"
channels = [
    { up = 0, down = 0, name = "debug", up_mode = "NoBlockSkip", format = "Defmt" },
]
timeout = 3000
show_timestamps = true

[default.gdb]
enabled = true
gdb_connection_string = "127.0.0.1:2345"
